cmake_minimum_required(VERSION 3.19)
project(RamConsumer LANGUAGES CXX)
if(ESL_RAM_SOURCE_DIR)
    add_subdirectory("${ESL_RAM_SOURCE_DIR}" ram-library)
else()
    find_package(AixEslRam 0.1 CONFIG REQUIRED)
endif()
add_executable(ram_consumer main.cpp)
target_link_libraries(ram_consumer PRIVATE aix::esl::ram)
enable_testing()
add_test(NAME external_ram_consumer COMMAND ram_consumer)
set_tests_properties(external_ram_consumer PROPERTIES TIMEOUT 15)
