cmake_minimum_required(VERSION 3.19)
project(AixEslBasicSystem LANGUAGES CXX)
if(ESL_MODELS_SOURCE_DIR)
    foreach(model ram rom host_master tlm_bus)
        if(NOT TARGET aix::esl::${model})
            add_subdirectory("${ESL_MODELS_SOURCE_DIR}/models/${model}" "models/${model}")
        endif()
    endforeach()
else()
    foreach(package AixEslRam AixEslRom AixEslHostMaster AixEslTlmBus)
        find_package(${package} 0.1 CONFIG REQUIRED)
    endforeach()
endif()
add_executable(basic_system systemc/main.cpp)
target_link_libraries(basic_system PRIVATE aix::esl::host_master aix::esl::tlm_bus aix::esl::ram aix::esl::rom)
enable_testing()
foreach(case normal concurrent drain capacity host_capacity transport invalid_map invalid_binding)
    add_test(NAME basic_${case} COMMAND basic_system ${case})
    set_tests_properties(basic_${case} PROPERTIES TIMEOUT 15)
endforeach()
